### ISSUE TITLE
AMS2 data

### ISSUE THREAD

**Issue by ghost** [viper4gh/SimHub-Plugin-CalcLngWheelSlip#11]
Hello viper,
Sorry to create a new issue but I didn't know any other mean to reach you.

Follow this is if you want a full car names list for AMS2
[https://drive.google.com/file/d/1rm8UTXZDtSzEBdjaPO9RgjgbX42SgL4X/view?usp=sharing](url)

**Comment by viper4gh** [comment]
@newtonpg 
it is ok doing it that way, an issue is not always a bug.
Thanks for the data, I released a new version 1.4.2a with an updated example file.
