### ISSUE TITLE
Read and save tyre diameters from and to file

### ISSUE THREAD

**Issue by viper4gh** [viper4gh/SimHub-Plugin-CalcLngWheelSlip#7]

**Comment by ghost** [comment]
If I'm not mistaken, editing data file to add a entry result a no reading value "-"

**Comment by viper4gh** [comment]
What did you exactly add?
Can you paste the file content here?
The car name must be exactly like in the SimHub CarModel Property.

**Comment by ghost** [comment]
Yes it is the very same CarModel

{
    "Automobilista2": {
        "Caterham 620R": [
            "0.534",
            "0.534",
            "0.569",
            "0.569",
         ],
		"Chevrolet Corvette C8.R": [
            "0.682",
            "0.682",
            "0.714",
            "0.714",
         ],
        "Formula Ultimate Gen2": [
            "0.72",
            "0.72",
            "0.72",
            "0.72",
         ]
    }
}

**Comment by ghost** [comment]
Sorry to bother you.
Run AMS2 again and again and again now it is working as expected.
Thank you.

**Comment by ghost** [comment]
This is the car data I have as of today.
You can use it as you wish.
Maybe a starting point to distribute along your new version of the plugin.

https://drive.google.com/file/d/1Bowu3N4VBJh31ArA0PAeJ4fMV4TQ1yzz/view?usp=sharing

PS: A phew (wishful thinking) Car Model were renamed in recent versions of AMS2 and need to be corrected.

**Comment by viper4gh** [comment]
Question: did you get the diameters from my Plugin or another source?
And there is maybe a special case, Indy Cars.
They use different configurations for road and oval courses and they have maybe different tyre diameters.
The question is if the different configurations are handled under different CarModel names or not.

**Comment by ghost** [comment]
Yes, all data are from your plugin although some times (when rears and fronts are different) the rear diameters are a little bit off thanks for some sliding while accelerating. I'm reviewing that but it takes time.
You can see that I'm not too addicted on openwheelers but I'll take a closer look in their CarModels.

**Comment by viper4gh** [comment]
The detection of the diameters happens only if you are within the defined limits, for example max 5% Throttle Input. That means the different between the accelerating tyres and the others should be low.
There are plugin settings available in SimHub for changing these limits, you can further reduce the Throttle Limit to for example 2%.
My favorite procedure is simply leaving the pit box, drive at the pit limiter and during driving in the pitlane I shortly go completely off throttle. This works most times, if the pit box is straight. Because in slight turns you normally hit the Velocity X (sideways) limit.

**Comment by ghost** [comment]
> There are plugin settings available in SimHub for changing these limits, you can further reduce the Throttle Limit to for example 2%.

My setting is 0% from 2 weeks. I think it is better to detect while decelerating.



> My favorite procedure is simply leaving the pit box, drive at the pit limiter and during driving in the pitlane I shortly go completely off throttle. This works most times, if the pit box is straight. Because in slight turns you normally hit the Velocity X (sideways) limit.

Agree while I prefer to press Clutch before off Throttle (SecondMonitor procedure).
and it appears that if Throttle limit is ok then Velocity is kind of ignored can you confirm please? Specially if resetting tyre diameter detection.

**Comment by ghost** [comment]
> The question is if the different configurations are handled under different CarModel names or not.

I can confirm that AMS2 have different Car Models for ovals and road course. While in ovals they append "CarModel - Speedway" so Formula USA 2023 became Formula USA 2023 - Speedway

There are also some road cars with additional low downforce pack, CarModel become "CarModel - Low Downforce"

**Comment by viper4gh** [comment]
> Agree while I prefer to press Clutch before off Throttle (SecondMonitor procedure). and it appears that if Throttle limit is ok then Velocity is kind of ignored can you confirm please? Specially if resetting tyre diameter detection.

After reseting the procedure should be the same as before, it uses the exactly same logic with the same limits. But I can check that again. With "Velocity" you mean the VelocityX Limit? 

And all limits should work independantly from each other. Throttle input in turns has maybe also an inpact on the sideways velocity. And the limit is not only the sideways Velocity, it is the ratio of VelocityX and Speed, because the higher the car speed the higher the sideways Velocity on same turn angle. This limit is not a perfect solution, but was the best way I found to eliminate sideways slip. 

Further small discrepancies for tyre diameters have in my opinion not a big impact for the slip calculation. In this case the zero value for slip is a bit shifted towards spin or lock, but it was mostly good enough for me.

Maybe we have the load and also save feature soon 😉 and then the detection is only needed one time and only for new cars and you then can finetune it in the file.

**Comment by viper4gh** [comment]
> I can confirm that AMS2 have different Car Models for ovals and road course. While in ovals they append "CarModel - Speedway" so Formula USA 2023 became Formula USA 2023 - Speedway
> 
> There are also some road cars with additional low downforce pack, CarModel become "CarModel - Low Downforce"

That's good, then we have no problem with it.

**Comment by ghost** [comment]
> Maybe we have the load and also save feature soon 😉 and then the detection is only needed one time and only for new cars and you then can finetune it in the file.

Very good!

**Comment by ghost** [comment]
> After reseting the procedure should be the same as before, it uses the exactly same logic with the same limits. But I can check that again. With "Velocity" you mean the VelocityX Limit?

No, sorry, it was the speed

**Comment by ghost** [comment]
> Further small discrepancies for tyre diameters have in my opinion not a big impact for the slip calculation. In this case the zero value for slip is a bit shifted towards spin or lock, but it was mostly good enough for me.

Agreed

**Comment by viper4gh** [comment]
> No, sorry, it was the speed

Ok, I will check that again. I think it is in km/h, but I will check that too.

**Comment by viper4gh** [comment]
> .... and it appears that if Throttle limit is ok then Velocity is kind of ignored can you confirm please? Specially if resetting tyre diameter detection.

I checked that again.
I increased the Throttle limit to 50% and the VelX limit to 0.0099, then I had only the speed as main minimum limit, which was default 50 km/h (it is km/h and not miles/h or m/s or something else, checked that too).
Then I tested with different cars in AMS2 and it was working like expected all the time. I had to increase speed to 50 km/h and at that moment the tyre diameter dectection was completed.
That was also working after I reset it with the key, I tested that also several times.

Further if you press the reset key if the car is driving faster than the configured speed limit, then you are directly within the limit again.

**Comment by ghost** [comment]
My bad, sorry!
I was triggering ResetTyreDiameter while on track, instead of CalcTyreDiameter.

**Comment by viper4gh** [comment]
> My bad, sorry! I was triggering ResetTyreDiameter while on track, instead of CalcTyreDiameter.

I am a little bit confused now.
The action **CalcTyreDiameter** completely ignores the limits and sets the tyre diameters immediatly by calculate it with the current available car telemetry. Further it overwrites the tyre diameters if they are already available (there is a bug with the new version following later, where the manual override by pressing the key produces errors if the tyre diameters are already in the JSON data, I will fix this next week).
The action **ResetTyreDiameter** deletes the saved tyre diameters and the tyre diameter detection logic starts from the beginning. If you press the key and at that moment all 4 limits are ok, then the detection is also completed immediatly.

**Comment by viper4gh** [comment]
https://drive.google.com/drive/folders/1IlkzfyAHcGlE9Gw8grgDPBYxEjty5PbS
New Alpha2 Version with read and write from and to file.
The JSON file structure has changed a bit, there are no quotes around the diameters anymore. Maybe you can update your file and provide it again, thanks. An example file is included.

**The logic should work as follows:**
- Starting SimHub, the tyre diameters are read from file in an internal JSON object
- If you start a session the tyre diameters are used from th JSON object, if they are not available the detection begins
- If a detection is completed the diameters are written into the JSON object, if you switch now to another car and back to this car again, the diameters are read from the JSON object
- If you close SimHub or switch to another game the file is read again and compared with the JSON object, if there are differences between them the file is overwritten on disk. The idea behind is to have less write operations on disk, if SimHub will crash during runtime the data is lost and not saved in the file.

**Special cases/problems:**
- If you start SimHub and there is no file, no data is read, but on closing SimHub or switching to another game, the file will be created with the new data
- If you reset the tyre diameters by the key action the diameters are also deleted in the JSON object, if you then close SimHub or switch to another game, they are also deleted in the file.
- manual override by pressing the key for CalcTyreDiameter is currently not working correct if the tyre diameters are already available in the JSON object, that means the SimHub properties should be updated, but not the JSON object and also not the file on closing SimHub or switching to another game
- there are no checks for the data quality or the syntax of the JSON file. If there are wrong characters or simply missing one or more tyre diameters per car, I don't know what happens.

Please check if it is working in general for you and if you will find some errors next to the mentioned above, please give me feedback. Thanks.

**Comment by viper4gh** [comment]
https://drive.google.com/drive/folders/1IlkzfyAHcGlE9Gw8grgDPBYxEjty5PbS
New Alpha3 Version with fix for manual override by pressing key for CalcTyreDiameter.
It was easier to fix as exptected, I hope it works.

**Comment by ghost** [comment]
Well, it worked!
Only thing is I can`t get to function the button mapped to trigger CalcTyreDiameter.
But ResetTyreDiameter do the job, so it`s ok

> * If you reset the tyre diameters by the key action the diameters are also deleted in the JSON object, if you then close SimHub or switch to another game, they are also deleted in the file.

Yes, can confirm.

> Maybe you can update your file and provide it again, thanks.

Updated now and will add new entries before send the link.

**Comment by viper4gh** [comment]
> Well, it worked! Only thing is I can`t get to function the button mapped to trigger CalcTyreDiameter. But ResetTyreDiameter do the job, so it`s ok
> 
This relates to my last update with the fix in Alpha3.
Did you use Alpha3?
I will check that again next week.

**Comment by ghost** [comment]
Yes, using alpha3
But I believe there's nothing wrong with the plugin, error is on my side.

This is the new data file
https://drive.google.com/file/d/1JM6o5f_i7JfXi6pXwM4tL9LnsZ8xWhBy/view?usp=sharing

**Comment by viper4gh** [comment]
> Yes, using alpha3 But I believe there's nothing wrong with the plugin, error is on my side.
> 
Maybe you can test to remap the keybinding. 
But as I already wrote I will also check it again, if there is no other problem. 

> This is the new data file https://drive.google.com/file/d/1JM6o5f_i7JfXi6pXwM4tL9LnsZ8xWhBy/view?usp=sharing

Thanks, but it seems that I have no access. Do you set it as public?

**Comment by ghost** [comment]
https://drive.google.com/file/d/1JM6o5f_i7JfXi6pXwM4tL9LnsZ8xWhBy/view?usp=sharing

**Comment by ghost** [comment]
Updated revised version of tyre diameter data (V3). This is all I have at this time.
The shared directory contains also a compressed backup of my SimHub\...\Plugins data\Automobilista2 where you can find under \cars all the redline limits I have so far. Enjoy if you wish.

https://drive.google.com/drive/folders/1se8mmQMP8vxRUqbtU1-mCubppu5TZix-?usp=sharing

PS: removed rF2 entries just because was having some issues editing data file. Please add it again.

**Comment by viper4gh** [comment]
@newtonpg 
Thanks for the data.
I checked the CalcTyreDiameter action again and it was working in my case.

Further I added some validation checks on reading the JSON file. Some things like syntax error, partly missing diameter values, wrong diameters (text instead of numbers, and I defined a valid range from 0.01 till 10 meters).
And the SimHub log shows an info for every problem.

Can you please check if all is still working for you in the new beta:
https://drive.google.com/drive/folders/1IlkzfyAHcGlE9Gw8grgDPBYxEjty5PbS

**Comment by ghost** [comment]
No issue on my side on the beta.

Added RX cars to the data, packed with V4. Car data are now sorted by Model and not more by Class followed by Model.

https://drive.google.com/drive/folders/1se8mmQMP8vxRUqbtU1-mCubppu5TZix-?usp=sharing

And now a minor thing, please don't bother to rectify.

How I bypass speed control (and also how to achieve better precision).
1. Assign 0% for throttle limit
2. Go for a ride and drive over the stablished speed limit
3. Press clutch and then gently release throttle
4. Soon and irrespective of the speed, tyre diameters will be accurately computed.

**Comment by viper4gh** [comment]
Thanks again, I will add the file to the release. I added a rF2 car again as example to understand the file structure.
And I changed the diameters for the 2023 Stock Cars, because they have 68 cm in the AMS2 Beta now.

Further I still want to understand the speed limit problem, because I tested as described and cannot reproduce it.
Maybe there is a misunderstanding.
The configured speed limit is a minimum limit. As long as you drive below the limit (for example 40 kph with a limit of 50 kph) then it is not working and the detection will not happen.
If you drive faster as the limit (for example 60 kph with the 50 kph limit) you are within the limit and the calculation will happen.
The slower you drive the more inaccurate is the calculation. Because of that we need a minimum speed for it, default 50 kph.
You wrote "Go for a ride and drive over the stablished speed limit", in this case the speed is ok for calculating the diameters.

At the beginning I also thought about using the clutch as a limit, but there are many players without a clutch out there and I discarded this plan again.

**Comment by ghost** [comment]
> I added a rF2 car again as example to understand the file structure.
> And I changed the diameters for the 2023 Stock Cars, because they have 68 cm in the AMS2 Beta now.

That's good! And I didn't perceived the changes in 2023 SC on Beta, thank you!

> The configured speed limit is a minimum limit.

Duh... I was thinking it as a window limit, something like speed to speed plus tolerance of say 5%.

> At the beginning I also thought about using the clutch as a limit, but there are many players without a clutch out there and I discarded this plan again.

Of course it would work if you have a clutch but if you don't have one you could alternatively go off throttle (with some delay internal limit or something else). Personally I suppose the most important (precision wise) is the car become decelerating to avoid the "normal" 1 to 2% of tyre slip at traction axle. But it is me and I'm not asking you to any change. The referred procedure is, in practical terms, independent of the car speed in diameter calculus and it cover my needs perfectly.

**Comment by viper4gh** [comment]
At the end the limits are always a compromise between perfection and usability (having a result in not too much time) .
It's supposed to work for people who don't deal with all that that much.
Or in other words the limits should prevent the biggest calculation errors.
For perfect results the calculation have to happen at a situation when the slip is completely zero.
Your procedure comes closer to this perfection.
My idea with a low limit for throttle was, that if you are on full throttle, then release it, and it fall below the limit, then it compensates the engine brake.
But this is car and setup dependant. 
But of course pressing the clutch completely removes the torque from the wheels, which is definitively better 😉

**Comment by ghost** [comment]
Congrats for v 1.3.3 and Thank You also for the reference!

**Comment by viper4gh** [comment]
@newtonpg 
Another question:
Because of the confusion with the limits, did you test the SimHub Overlay which is included in the Releases?
I ask because there you can perfectly see how the limits working during the detection phase. And only when all values are green, the detection is completed.

**Comment by ghost** [comment]
Yes, I always run the overlay v1.3.2a with slight visual-only modifications like a transparent background.
Didn`t reinstall the overlays since alphas and beta looks like equal to the last version.
Do you advice for a new install?

**Comment by viper4gh** [comment]
No, there were no changes, it is the same since several versions.

**Comment by viper4gh** [comment]
Feature implemented.
